#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.5
# from Racc grammer file "".
#

require 'racc/parser.rb'

require 'strscan'

class MMLanguageParser < Racc::Parser

module_eval(<<'...end mml.grammar/module_eval...', 'mml.grammar', 124)

def unquote(value)
  case value
  when /^'(.*)'$/ then $1
  when /^"(.*)"$/ then $1
  else value
  end
end

def parse(str, runtime)
  @input = str.to_s
  tokens = []
  scanner = StringScanner.new(@input)

  until scanner.eos?
    case
    when scanner.scan(/\s+/)
      # ignore space
    when m = scanner.scan(/\d+\b/i)
      tokens.push [:NUMBER, m]
    when m = scanner.scan(/#\{[^}]*\}/)
      m =~ /#\{([^}]*)\}/
      if $1.nil? || $1.empty?
        raise '\'#{}\' is used to specify variable in the script, must have variable name specified'
      elsif runtime[$1.to_sym].nil?
        tokens.push [:IDENTIFIER, m]
      else
        tokens.push [:IDENTIFIER, runtime[$1.to_sym]]
      end
    when m = scanner.scan(/#\b/i)
      tokens.push [:CARD, m]
    when m = scanner.scan(/with\b/i)
      tokens.push [:WITH, m]
    when m = scanner.scan(/,/)
      tokens.push [:COMMA, m]
    when m = scanner.scan(/=>/)
      tokens.push [:MAP_TO, m]
    when m = scanner.scan(/=/)
      tokens.push [:EQUAL, m]
    when m = scanner.scan(/view\b/i)
      tokens.push [:VIEW, m]
    when m = scanner.scan(/\(([^\)]*)\)/)
      m =~ /\(([^\)]*)\)/
      tokens.push [:COMMENT, $1]
    when m = scanner.scan(/'([^']*)'/)
      tokens.push [:IDENTIFIER, unquote(m)]
    when m = scanner.scan(/"([^"]*)"/)
      tokens.push [:IDENTIFIER, unquote(m)]
    when m = scanner.scan(/`[^`]*`?/)
      m =~ /`([^`]*)`?/
      tokens.push [:SYSTEM_CMD, $1]
    when m = scanner.scan(/[\w]+/)
      tokens.push [:IDENTIFIER, m]
    else
      raise "unexpected characters #{scanner.peek(5)}"
    end
  end

  runtime[:context].push(tokens)
  
  tokens.push [false, false]
  yyparse(tokens, :each)
end

def on_error(error_token_id, error_value, value_stack)
  msg = "Could not parse MML: #{@input}, error_token_id: #{error_token_id}, error_value: #{error_value}"
  msg << "\nafter #{value_stack.last}" if value_stack.length > 1
  msg << "\n(This could be due to invalid formatting, including whitespace and indentation."
  msg << " Please check your MML statement and try again.)"
  raise ParseError, msg
end
...end mml.grammar/module_eval...
##### State transition tables begin ###

racc_action_table = [
     2,    26,    12,    37,     2,    12,    27,    36,     5,     7,
    23,    25,    11,     1,    19,    12,    16,    17,    34,    35,
    16,    17,    16,    17,    50,    51,    16,    17,    16,    17,
    16,    17,    15,    14,    40,    41,    26,    44,    45,    46,
    48,    40,    12,    33 ]

racc_action_check = [
    10,    10,    14,    24,     0,    12,    10,    24,     0,     0,
    10,    10,     0,     0,     5,     5,     4,     4,    19,    19,
     7,     7,     8,     8,    46,    46,    11,    11,    13,    13,
    47,    47,     3,     2,    26,    27,    28,    37,    39,    40,
    42,    45,     1,    15 ]

racc_action_pointer = [
     2,    36,    26,    32,     4,     9,   nil,     8,    10,   nil,
    -2,    14,    -1,    16,    -4,    43,   nil,   nil,   nil,    12,
   nil,   nil,   nil,   nil,    -5,   nil,    28,    23,    33,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    25,   nil,    29,
    35,   nil,    32,   nil,   nil,    35,    18,    18,   nil,   nil,
   nil,   nil,   nil ]

racc_action_default = [
   -34,   -34,   -34,   -34,   -20,   -32,   -25,   -20,   -20,    -5,
    -8,   -20,   -32,   -20,   -18,   -34,   -21,   -22,    -1,   -34,
   -33,    -9,    -4,    -6,   -34,    -7,   -34,   -34,   -14,    -3,
    -2,   -26,   -19,    53,   -23,   -24,   -12,   -34,   -27,   -28,
   -34,   -13,   -16,   -15,   -11,   -34,   -34,   -20,   -17,   -29,
   -30,   -31,   -10 ]

racc_goto_table = [
    18,    38,     8,    21,    22,    24,    10,    29,     9,    30,
     6,    13,    28,    42,    47,     4,    31,     3,   nil,   nil,
    49,   nil,   nil,    43,    32,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    52 ]

racc_goto_check = [
     3,    12,     5,     3,     3,    10,     7,     3,     6,     3,
     4,     4,     5,     8,     9,     2,    11,     1,   nil,   nil,
    12,   nil,   nil,    10,     4,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,    17,    15,    -4,    10,     2,     8,     6,   -15,   -28,
    -5,     2,   -25,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,    20,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    39 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 15, :_reduce_1,
  3, 15, :_reduce_2,
  2, 15, :_reduce_3,
  2, 15, :_reduce_4,
  1, 15, :_reduce_5,
  2, 15, :_reduce_6,
  2, 15, :_reduce_7,
  1, 15, :_reduce_8,
  2, 15, :_reduce_9,
  5, 20, :_reduce_10,
  4, 20, :_reduce_11,
  3, 20, :_reduce_12,
  3, 20, :_reduce_13,
  0, 22, :_reduce_14,
  1, 22, :_reduce_none,
  0, 23, :_reduce_16,
  1, 23, :_reduce_17,
  0, 25, :_reduce_18,
  1, 25, :_reduce_19,
  0, 17, :_reduce_20,
  1, 17, :_reduce_21,
  1, 17, :_reduce_22,
  3, 16, :_reduce_23,
  3, 16, :_reduce_24,
  1, 21, :_reduce_25,
  3, 19, :_reduce_26,
  2, 24, :_reduce_27,
  1, 26, :_reduce_28,
  3, 26, :_reduce_29,
  3, 27, :_reduce_30,
  3, 27, :_reduce_31,
  1, 18, :_reduce_32,
  2, 18, :_reduce_33 ]

racc_reduce_n = 34

racc_shift_n = 53

racc_token_table = {
  false => 0,
  :error => 1,
  :CARD => 2,
  :WITH => 3,
  :MAP_TO => 4,
  :EQUAL => 5,
  :IDENTIFIER => 6,
  :NUMBER => 7,
  :COMMENT => 8,
  :COMMA => 9,
  :SYSTEM_CMD => 10,
  :VIEW => 11,
  :CARD_RESOURCE => 12,
  :VIEW_RESOURCE => 13 }

racc_nt_base = 14

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "CARD",
  "WITH",
  "MAP_TO",
  "EQUAL",
  "IDENTIFIER",
  "NUMBER",
  "COMMENT",
  "COMMA",
  "SYSTEM_CMD",
  "VIEW",
  "CARD_RESOURCE",
  "VIEW_RESOURCE",
  "$start",
  "target",
  "runtime_variable",
  "opt_workspace",
  "identifiers",
  "card",
  "transition",
  "command_name",
  "opt_user_entered_properties",
  "opt_comment",
  "user_entered_properties",
  "opt_attrs",
  "properties",
  "property" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'mml.grammar', 17)
  def _reduce_1(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 19)
  def _reduce_2(val, _values)
    MM::Console::View.new(val[1].join(' '))
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 21)
  def _reduce_3(val, _values)
    MM::Console::SystemCmd.new(val[0])
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 23)
  def _reduce_4(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 25)
  def _reduce_5(val, _values)
    MM::Console::Transition.new(val[0])
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 27)
  def _reduce_6(val, _values)
    MM::Console::CardResourceCommand.new(val[0], val[1])
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 29)
  def _reduce_7(val, _values)
    MM::Console::NoResourceCommand.new(val[0])
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 31)
  def _reduce_8(val, _values)
    MM::Console::NoResourceCommand.new(val[0])
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 33)
  def _reduce_9(val, _values)
    MM::Console::SelectIndexCommand.new(val[0].to_i)
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 38)
  def _reduce_10(val, _values)
    {
      :command => val[0],
      :card_number => val[1].number,
      :properties => val[2],
      :comment => val[3]
    }
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 45)
  def _reduce_11(val, _values)
    {
      :command => val[0],
      :properties => val[1],
      :comment => val[2],
      :card_number => val[3].number
    }
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 52)
  def _reduce_12(val, _values)
    {
      :command => val[0],
      :properties => val[1],
      :card_number => val[2].number
    }
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 58)
  def _reduce_13(val, _values)
    {
      :command => val[0],
      :comment => val[1],
      :card_number => val[2].number
    }
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 66)
  def _reduce_14(val, _values)
     nil 
  end
.,.,

# reduce 15 omitted

module_eval(<<'.,.,', 'mml.grammar', 71)
  def _reduce_16(val, _values)
     nil 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 72)
  def _reduce_17(val, _values)
     val[0] 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 76)
  def _reduce_18(val, _values)
     nil 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 77)
  def _reduce_19(val, _values)
     val[0] 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 81)
  def _reduce_20(val, _values)
     nil 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 82)
  def _reduce_21(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 83)
  def _reduce_22(val, _values)
    val[0]
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 87)
  def _reduce_23(val, _values)
    MM::Console::RuntimeVariable.new(:name => val[0], :value => val[2])
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 88)
  def _reduce_24(val, _values)
    MM::Console::RuntimeVariable.new(:name => val[0], :value => val[2])
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 92)
  def _reduce_25(val, _values)
     val[0].join(" ") 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 96)
  def _reduce_26(val, _values)
     MM::Console::Card.new(val[1].to_i, val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 100)
  def _reduce_27(val, _values)
     val[1] 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 104)
  def _reduce_28(val, _values)
     [val[0]] 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 105)
  def _reduce_29(val, _values)
     [val[0]] + val[2] 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 109)
  def _reduce_30(val, _values)
     { :name => val[0], :value => val[2] } 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 110)
  def _reduce_31(val, _values)
     { :name => val[0], :value => val[2] } 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 114)
  def _reduce_32(val, _values)
     [val[0]] 
  end
.,.,

module_eval(<<'.,.,', 'mml.grammar', 115)
  def _reduce_33(val, _values)
     [val[0]] + val[1] 
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

end   # class MMLanguageParser
