require 'mm/console/simple_command/base'
require 'mm/console/simple_command/runtime_variables'
require 'mm/console/simple_command/clean_cache'
require 'mm/console/simple_command/tabs'
require 'mm/console/simple_command/help'
require 'mm/console/simple_command/todo'
